---
# Ansible Cisco ACI Documentation by Freitas
- hosts: localhost
  gather_facts: false

  vars:
   msg: |
        Bem vindo ao Inventário do ACI - by NTT 
  tasks:
    - name: "Remove Existing Working Directory"
      file:
        path: roles/ansible_temp_dir
        state: absent
      tags: always

    - name: "Instructions"
      debug:
        msg: "{{ msg.split('\n') }}"
      tags: always             

- hosts: apic
  any_errors_fatal: false
  roles:
    - role: query

  vars_prompt:

  - name: "apic_ip"
    prompt: "Entre como o IP ou hostname da APIC: "
    private: no

  - name: "user"
    prompt: "Entre com o usuário da APIC: "
    private: no
    unsafe: yes
    default: 'admin'

  - name: "pass"
    prompt: "Enter com a senha da APIC: "
    private: yes
    unsafe: yes

  - name: "report_name"
    prompt: "Entre com o nome que deseja salvar o relatório"
    private: no
    default: 'noname-report'
